DependencyInjectionWshop/Controllers/FoodController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DependencyInjectionWshop.Models;
using Microsoft.AspNetCore.Mvc;

namespace DependencyInjectionWshop.Controllers
{
    public class FoodController : Controller
    {
        private readonly AppData appData;

        public FoodController(AppData appData)
        {
            this.appData = appData;
        }

        public IActionResult Index()
        {
            ViewData["photos"] = appData.Food;

            // to highlight "Food" as the selected menu-item
            ViewData["Is_Food"] = "bold_menu";

            // use sessionId to determine if user has already logged in
            string sessionId = Request.Cookies["sessionId"];
            if (sessionId != null)
            {
                User user = appData.Users.Find(x => x.SessionId == sessionId);
                if (user == null)
                    return RedirectToAction("Index", "Logout");

                ViewData["sessionId"] = sessionId;
                ViewData["likes"] = user.Likes;
            }

            return View("ImageGallery");
        }
    }
}

DependencyInjectionWshop/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using DependencyInjectionWshop.Models;

namespace DependencyInjectionWshop.Controllers
{
    public class LoginController : Controller
    {
        private readonly AppData appData;

        public LoginController(AppData appData)
        {
            this.appData = appData;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Authenticate(string username, string password)
        {
            User user = appData.Users.Find(x => x.Username == username &&
                x.Password == password);

            if (user == null)
            {
                ViewData["username"] = username;
                ViewData["errMsg"] = "No such user or incorrect password.";

                return View("Index");
            }
            else
            {
                user.SessionId = Guid.NewGuid().ToString();
                Response.Cookies.Append("sessionId", user.SessionId);

                return RedirectToAction("Index", "Office");
            }
        }
    }  
}

DependencyInjectionWshop/Controllers/TravelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DependencyInjectionWshop.Models;
using Microsoft.AspNetCore.Mvc;

namespace DependencyInjectionWshop.Controllers
{
    public class TravelController : Controller
    {
        private readonly AppData appData;

        public TravelController(AppData appData)
        {
            this.appData = appData;
        }

        public IActionResult Index()
        {
            ViewData["photos"] = appData.Travel;

            // to highlight "Travel" as the selected menu-item
            ViewData["Is_Travel"] = "bold_menu";

            // use sessionId to determine if user has already logged in
            string sessionId = HttpContext.Request.Cookies["sessionId"];
            if (sessionId != null)
            {
                User user = appData.Users.Find(x => x.SessionId == sessionId);
                if (user == null)
                    return RedirectToAction("Index", "Logout");

                ViewData["sessionId"] = sessionId;
                ViewData["likes"] = user.Likes;
            }

            return View("ImageGallery");
        }
    }
}

DependencyInjectionWshop/Views/Shared/ImageGallery.cshtml
@{
    ViewData["Title"] = "Gallery Page";

    var photos = (List<Photo>)ViewData["photos"];
    var likes = (List<string>)ViewData["likes"];
}

@section Scripts
    {
    <script src="~/js/shared/image_gallery.js"></script>
}


<style>
    table {
        width: 100%;
        margin: auto;
    }

    .badge {
        font-size: 14px !important;
    }

    .like_icon {
        width: 40px;
        height: 40px;
        position: absolute;
        top: 5px;
        right: 30px;
        cursor: pointer;
    }

    .img_container {
        position: relative;
    }

    .badge_container {
        position: absolute;
        left: 10px;
        bottom: 10px;
        opacity: 0.7;
    }

    .bold_menu {
        font-weight: bold;
    }

    button {
        position:absolute;
        bottom: 10px;
        right: 30px;
        
        
    }
</style>
<div class="input-group">
    
    <input autofocus placeholder="search" class="from-control" type="text" autocomplete="off" name="search"/>
</div>
<br>
<br />
<table>


    @for (int i = 0; i < photos.Count; i++)
    {
        @*string[] atag = tags[i].Split(",");*@

        if (i % 3 == 0)
        {
            @:<tr>
            }


            @:<td>
                @:<div class="img_container">
                    @:<img src=@photos[i].Url width="350" height="235" />
                    @:<button id="add">Add</button>
                    if (ViewData["sessionId"] != null)
                    {
                        string icon_link = "/img/like_gray.png";

                        string id = likes.Find(x => x == photos[i].Id);
                        if (id != null)
                        {
                            icon_link = "/img/like.png";

                        }

                        @:<img src=@icon_link class="like_icon" id=@photos[i].Id />
                    }

                    @:<div class="badge_container">
                        @for (int k = 0; k < photos[i].Tags.Count; k++)
                        {
                            @:<span class="badge badge-pill badge-dark">@photos[i].Tags[k]</span>
                        }
                    @:</div>


                @:</div>
            @:</td>






















            if ((i + 1) % 3 == 0)
            {
            @:</tr>


        }

    }

</table>

DependencyInjectionWshop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DependencyInjectionWshop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Office" asp-action="Index">DependencyInjectionWshop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark @ViewData["Is_Office"]"
                               asp-controller="Office" asp-action="Index">Office</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark @ViewData["Is_Travel"]"
                               asp-controller="Travel" asp-action="Index">Travel</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark @ViewData["Is_Food"]"
                               asp-controller="Food" asp-action="Index">Food</a>
                        </li>
                    </ul>
                </div>
                <div style="float:right">
                    @if (ViewData["sessionId"] == null)
                    {
                        <a class="nav-link text-dark" asp-controller="Login" asp-action="Index">Login</a>                        
                    }
                    else
                    {
                        <a class="nav-link text-dark" asp-controller="Logout" asp-action="Index">Logout</a>
                    }
                </div>
                <div style= float: right;
                     margin-right: 100px>
                    <p>Cart: </p>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>